[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' code.tidio.co *.tidio.co cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' code.tidio.co *.tidio.co cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; img-src 'self' data: *.tidio.co; connect-src 'self' *.tidio.co wss://*.tidio.co; frame-src *.tidio.co;" 